In [1]:
import pandas as pd
import numpy as np
import ast # Abstract syntax tree

In [2]:
movies = pd.read_csv("movies.csv")
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [3]:
credits = pd.read_csv("credits.csv")
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [4]:
data = movies.merge(credits,on = "title")
data.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
data = data[["id","title","genres","keywords","overview","cast","crew"]]
data.head()

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
data.isnull().sum()

id          0
title       0
genres      0
keywords    0
overview    3
cast        0
crew        0
dtype: int64

In [7]:
data.dropna(inplace = True)
data.isnull().sum()

id          0
title       0
genres      0
keywords    0
overview    0
cast        0
crew        0
dtype: int64

In [8]:
data.duplicated().sum()

0

In [9]:
data.iloc[0].genres # it is like a  string enclosed list of dictionary

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [10]:
def convert(obj):
    lst = []
    for i in ast.literal_eval(obj):    # literal_eval() used to convert string enclosed list to the list
        lst.append(i["name"])
    return lst

In [11]:
data["genres"] = data["genres"].apply(convert)
data["keywords"] = data["keywords"].apply(convert)
data.head()

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [12]:
def convert2(obj):
    lst = []
    counter = 0
    for i in ast.literal_eval(obj):     # literal_eval() used to convert string enclosed list to the list
        if(counter != 3):
            lst.append(i["name"])
        else:
            break;
            
    return lst

In [13]:
data["cast"] = data["cast"].apply(convert2)
data.head()

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
def fetch_director_from_crew(obj):
    lst = []
    for i in ast.literal_eval(obj):  # literal_eval() used to convert string enclosed list to the list
        if(i["job"] == "Director"):
            lst.append(i["name"])
            break;
    return lst

In [15]:
data["crew"] = data["crew"].apply(fetch_director_from_crew)
data.head()

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [16]:
data["genres"] = data["genres"].apply(lambda x: [i.replace(" ","") for i in x ])
data["keywords"] = data["keywords"].apply(lambda x: [i.replace(" ","") for i in x ])
data["cast"] = data["cast"].apply(lambda x: [i.replace(" ","") for i in x ])
data["crew"] = data["crew"].apply(lambda x: [i.replace(" ","") for i in x ])
data.head()

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","In the 22nd century, a paraplegic Marine is di...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","Captain Barbossa, long believed to be dead, ha...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",A cryptic message from Bondâ€™s past sends him o...,"[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",Following the death of District Attorney Harve...,"[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","John Carter is a war-weary, former military ca...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [17]:
data["overview"] = data["overview"].apply(lambda x: x.split())
data.head()

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [18]:
data["tags"] =  data["overview"] + data["genres"] + data["keywords"] + data["cast"] + data["crew"]
data.head()

,id,title,genres,keywords,overview,cast,crew,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [19]:
data = data[["id","title","tags"]]
data.head()

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [20]:
data["tags"] = data["tags"].apply(lambda x: [i.lower() for i in x])
data["tags"] = data["tags"].apply(lambda x: " ".join(x))
data.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [21]:
# converting every movie to a vector 

from sklearn.feature_extraction.text import CountVectorizer  # This class help us to covert each movie tags to a vector
cv = CountVectorizer(max_features = 4000,stop_words = "english")

In [22]:
vectors = cv.fit_transform(data["tags"]).toarray()
vectors.shape

(4806, 4000)

In [23]:
cv.get_feature_names()

C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '1930s',
 '1940s',
 '1950s',
 '1960s',
 '1970s',
 '1980s',
 '19th',
 '19thcentury',
 '20',
 '20th',
 '24',
 '30',
 '3d',
 '40',
 '50',
 'aaroneckhart',
 'aasifmandvi',
 'abandoned',
 'abigailbreslin',
 'ability',
 'able',
 'abuse',
 'academy',
 'accepts',
 'accident',
 'accidentally',
 'accompanied',
 'account',
 'accused',
 'act',
 'action',
 'actions',
 'activist',
 'activities',
 'actor',
 'actors',
 'actress',
 'actually',
 'adam',
 'adambrody',
 'adamgoldberg',
 'adamlefevre',
 'adams',
 'adamsandler',
 'adamscott',
 'adamshankman',
 'adaptation',
 'addiction',
 'adewaleakinnuoye',
 'adopted',
 'adoption',
 'adrienbrody',
 'adult',
 'adultery',
 'adults',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'aftercreditsstinger',
 'afterlife',
 'agbaje',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agent',
 'agents',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aidanquinn',
 'aided',
 'aids',
 'air',
 'airplane',
 'airport',
 'al',
 'alanalda',
 'alanarkin',
 'alancumming',
 'alanrickman',
 'alantudyk',
 'alaska',
 'albert',
 'albertbrooks',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alexapenavega',
 'alfredhitchcock',
 'alfredmolina',
 'alfrewoodard',
 'alice',
 'alien',
 'alieninvasion',
 'aliens',
 'alike',
 'alilarter',
 'alive',
 'allen',
 'allencovert',
 'alliance',
 'allied',
 'allies',
 'allisonjanney',
 'allows',
 'ally',
 'alpacino',
 'alter',
 'alternate',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amazing',
 'ambassador',
 'amberheard',
 'ambition',
 'ambitious',
 'ambush',
 'america',
 'american',
 'americanfootball',
 'americans',
 'amnesia',
 'amp',
 'amy',
 'amyadams',
 'amypoehler',
 'amyryan',
 'amysedaris',
 'amysmart',
 'ancient',
 'anderson',
 'andiemacdowell',
 'andreamartin',
 'andrew',
 'andrewdaly',
 'android',
 'andy',
 'andydick',
 'andygarcÃ­a',
 'andyrichter',
 'andysamberg',
 'andyserkis',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'anger',
 'angry',
 'animal',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'anjelicahuston',
 'ann',
 'anna',
 'annafaris',
 'annakendrick',
 'annapaquin',
 'anndowd',
 'anne',
 'annefletcher',
 'annehathaway',
 'anneheche',
 'annemoss',
 'annettebening',
 'annie',
 'annual',
 'answer',
 'answers',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthonymackie',
 'anti',
 'antihero',
 'antonicorone',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartment',
 'ape',
 'apocalypse',
 'apocalyptic',
 'appears',
 'apple',
 'apprentice',
 'april',
 'archaeologist',
 'architect',
 'area',
 'arena',
 'armed',
 'arms',
 'armstrong',
 'army',
 'arnoldschwarzenegger',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'art',
 'arthur',
 'arthurj',
 'artificialintelligence',
 'artist',
 'artists',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asked',
 'asks',
 'aspiring',
 'assassin',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assistant',
 'astronaut',
 'asylum',
 'athlete',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempts',
 'attention',
 'attitude',
 'attorney',
 'attractive',
 'audition',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'auto',
 'avenge',
 'avoid',
 'awakens',
 'award',
 'away',
 'awry',
 'baby',
 'bachelor',
 'backdrop',
 'bad',
 'bailey',
 'baker',
 'balance',
 'ball',
 'ballet',
 'band',
 'bank',
 'banker',
 'bar',
 'barely',
 'barn',
 'barney',
 'barry',
 'barrylevinson',
 'barrypepper',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battles',
 'battling',
 'beach',
 'bear',
 'beast',
 'beat',
 'beautiful',
 'beauty',
 'becominganadult',
 'bed',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'believe',
 'believed',
 'believes',
 'beloved',
 'ben',
 'benaffleck',
 'benedictcumberbatch',
 'benfoster',
 'beniciodeltoro',
 'benjaminbratt',
 'benkingsley',
 'benmendelsohn',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'bernardhill',
 'berniemac',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'bethgrant',
 'betrayal',
 'bettemidler',
 'better',
 'bible',
 'big',
 'biggest',
 'biker',
 'billcobbs',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billnunn',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billyburke',
 'billyconnolly',
 'billycrudup',
 'billycrystal',
 'billyzane',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackmail',
 'blackpeople',
 'blade',
 'blake',
 'blind',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boat',
 'bob',
 'bobbalaban',
 'bobby',
 'bobbycannavale',
 'bobgunton',
 'bobhoskins',
 'body',
 'bodyguard',
 'bokeemwoodbine',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bonniehunt',
 'book',
 'books',
 'border',
 'bored',
 'born',
 'boss',
 'boston',
 'bound',
 'bounty',
 'bountyhunter',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boydbanks',
 'boyfriend',
 'boys',
 'braddourif',
 'bradgarrett',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brave',
 'bravery',
 'break',
 'breaking',
 'breaks',
 'breckinmeyer',
 'brendanfraser',
 'brendangleeson',
 'brentbriscoe',
 'brentspiner',
 'brian',
 'briancox',
 'briandennehy',
 'briandepalma',
 'briandoyle',
 'brianj',
 'bride',
 'bridge',
 'brielarson',
 'brien',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'brooklyn',
 'brooks',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucecampbell',
 'brucedern',
 'brucegreenwood',
 'brucemcgill',
 'brucespence',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryan',
 'bryancranston',
 'brycedallashoward',
 'buddy',
 'build',
 'building',
 'built',
 'bully',
 'bumbling',
 'buried',
 'burtreynolds',
 'bus',
 'bush',
 'business',
 'businessman',
 'busy',
 'butler',
 'buy',
 'byrne',
 'cabin',
 'california',
 'called',
 'calls',
 'callumkeithrennie',
 'calvin',
 'came',
 'camera',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'camping',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'cannibal',
 'capable',
 'capitalism',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'caraseymour',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'careymulligan',
 'caribbean',
 'carl',
 'carlagugino',
 'carmen',
 'carmenelectra',
 'carolineaaron',
 'carolinegoodall',
 'carpenter',
 'carrace',
 'carrie',
 'carriefisher',
 'carry',
 'carrying',
 'cars',
 'carter',
 'cary',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'catch',
 'catches',
 'cateblanchett',
 'catherinekeener',
 'catherineo',
 'catherinezeta',
 'cathey',
 'catholic',
 'catholicism',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cave',
 'cedrictheentertainer',
 'celebrate',
 'celebration',
 'celebrity',
 'celiaimrie',
 'celiaweston',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'certain',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'chancekelly',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlesdance',
 'charlesdurning',
 'charless',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotterampling',
 'charltonheston',
 'charming',
 'chase',
 'chazzpalminteri',
 'cheating',
 'cheechmarin',
 'chef',
 'chevychase',
 'chicago',
 'chief',
 'child',
 'childabuse',
 'childhood',
 'children',
 'chilling',
 'chimcbride',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloÃ«gracemoretz',
 'chloÃ«sevigny',
 'choice',
 'choose',
 'chosen',
 'chris',
 'chriscooper',
 'chrisellis',
 'chrisevans',
 'chrishemsworth',
 'chrismessina',
 'chrismiller',
 'chriso',
 'chrispine',
 'chrispratt',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christinebaranski',
 'christmas',
 'christmasparty',
 'christopher',
 'christopherguest',
 'christopherlee',
 'christopherlloyd',
 'christophermcdonald',
 'christophermeloni',
 'christophermintz',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chronicles',
 'church',
 'cia',
 'ciarÃ¡nhinds',
 'cillianmurphy',
 'circle',
 'circumstances',
 'circus',
 'citizens',
 'city',
 'civil',
 'civilwar',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'claireforlani',
 'clan',
 'clancybrown',
 'clark',
 'clarkgregg',
 'clash',
 'class',
 'classic',
 'classmate',
 'claudevandamme',
 'cleaduvall',
 'clean',
 'clear',
 'clerk',
 'client',
 'cliffcurtis',
 'cliftoncollinsjr',
 'climbing',
 'clinteastwood',
 'clinthoward',
 'cliveowen',
 'clock',
 'clone',
 'clorisleachman',
 'close',
 'closer',
 'club',
 'clues',
 'coach',
 'coast',
 'cocaine',
 'code',
 'cohen',
 'cold',
 'coldwar',
 'cole',
 'colehauser',
 'colinfarrell',
 'colinfirth',
 'colinhanks',
 'colinsalmon',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'colleencamp',
 'college',
 'collide',
 'collins',
 'colmfeore',
 'colonel',
 'colony',
 'colorful',
 'coma',
 'combat',
 'come',
 'comedian',
 'comedy',
 'comes',
 'comic',
 'coming',
 'comingofage',
 'comingout',
 'commander',
 'commit',
 'commitment',
 'committed',
 'common',
 'community',
 'company',
 'compete',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'computer',
 'concert',
 'condition',
 'confidence',
 'conflict',
 'confront',
 'congress',
 'connected',
 'connection',
 'connell',
 'connor',
 'conquer',
 'conradvernon',
 'consequences',
 'conspiracy',
 'contact',
 'contest',
 'continue',
 'continues',
 'contract',
 'control',
 'controversial',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'coreyburton',
 'corporate',
 'corporation',
 'corpse',
 'corrupt',
 'corruption',
 'cost',
 'count',
 'country',
 'countryside',
 'couple',
 'couples',
 'courage',
 'course',
 'court',
 'courtcase',
 'cousin',
 'cover',
 'covert',
 'cowardliness',
 'cowboy',
 'crack',
 'craig',
 'craigrobinson',
 'craigt',
 'crash',
 'crashes',
 'crazy',
 'create',
 'created',
 'creates',
 'creature',
 'creatures',
 'crew',
 'crime',
 'crimefighter',
 'crimes',
 'criminal',
 'criminals',
 'crisis',
 'crispinglover',
 'crocodile',
 'cross',
 'crossed',
 'cruel',
 'cruise',
 'crush',
 'cuba',
 'cubagoodingjr',
 'cult',
 'cultfilm',
 'cultural',
 'culture',
 'cultureclash',
 'cure',
 'current',
 'curse',
 'custody',
 'cut',
 'cyberpunk',
 'cyborg',
 'dad',
 'daily',
 'dakotafanning',
 'dan',
 'danaykroyd',
 'dance',
 'dancer',
 'dancing',
 'danger',
 'dangerous',
 'danhedaya',
 'daniel',
 'danielcraig',
 'danielmays',
 'danielvonbargen',
 'danny',
 'dannydevito',
 'dannyglover',
 'dannyhuston',
 'dannymann',
 'dannymcbride',
 'dannytrejo',
 'dark',
 'darkcomedy',
 'darkness',
 'darylhannah',
 'dashmihok',
 'date',
 'dating',
 'daughter',
 'daughters',
 'dave',
 'davefranco',
 'david',
 'davidalangrier',
 'davidarquette',
 'davidbradley',
 'davidcross',
 'davidjensen',
 'davidkoechner',
 'davidkrumholtz',
 'davidmorse',
 'davido',
 'davidoyelowo',
 'davidpaymer',
 'davidspade',
 'davidstrathairn',
 'davidthewlis',
 'davidwarshofsky',
 'davies',
 'davis',
 'daxshepard',
 'day',
 'days',
 'dccomics',
 'dea',
 'dead',
 'deadly',
 'deal',
 'dealer',
 'dealers',
 'dealing',
 'deals',
 'dean',
 'deannorris',
 'death',
 'deathofafriend',
 'debt',
 'decades',
 'deceased',
 'deceit',
 'deception',
 'decide',
 'decided',
 'decides',
 'decision',
 'decisions',
 'deep',
 'deeper',
 'deeply',
 'deeproy',
 'defeat',
 'defend',
 'defense',
 'delroylindo',
 'delusion',
 'demands',
 'demimoore',
 'demon',
 'demons',
 'denisleary',
 'deniso',
 'dennisdugan',
 'dennisfarina',
 'dennishaysbert',
 'dennishopper',
 'dennisquaid',
 'dentist',
 'denzelwashington',
 'department',
 'depressed',
 'depression',
 'deranged',
 'derekjacobi',
 'derekluke',
 'dermotmulroney',
 'desert',
 'desire',
 'desmondllewelyn',
 'despair',
 'desperate',
 'desperately',
 'despite',
 'destined',
 'destiny',
 'destroy',
 'destroyed',
 'destroying',
 'destruction',
 'details',
 'detective',
 'detectives',
 'determined',
 'detroit',
 'develop',
 'develops',
 'device',
 'devil',
 'devoted',
 'dexterfletcher',
 'diamond',
 'diane',
 'dianekeaton',
 'dianekruger',
 'dianelane',
 'diannewiest',
 'diary',
 'dick',
 'dickmiller',
 'dictator',
 'did',
 ...]

In [24]:
from sklearn.metrics.pairwise import cosine_similarity    # it gives us value betweeen 0 to 1 , it helps to find out how much the two vectors are similar
similarity = cosine_similarity(vectors)
similarity.shape

(4806, 4806)

In [25]:
def recommend(movie):
    movie_index = data[data["title"] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse = True,key = lambda x : x[1])[1:6]
    
    for i in movies_list:
        print(data.iloc[i[0]].title)

In [26]:
recommend("Batman Begins")

The Dark Knight
The Dark Knight Rises
Batman
Amidst the Devil's Wings
Batman & Robin

In [27]:
import pickle

In [28]:
pickle.dump(data.to_dict(),open("temp.txt","wb")) # syntax of " dump(object,fileObj) "

In [29]:
pickle.dump(similarity,open("similarity.txt","wb"))